### PR TITLE
Removing a breaking change that is introduced through the IDS Informa…

### PR DESCRIPTION
**Pull request by sebbader**
…tion Model Java Lib Version 5.0.0-SNAPSHOT

### CODE REVIEW

**Comment by sebbader** [comment]
In particular, it shall solve the RejectionMessage "securityProfile not set" when registering a Connector with:
```
...

  "ids:securityProfile" : {
    "@id" : "https://w3id.org/idsa/code/BASE_SECURITY_PROFILE"
  },
  ...
```

**Comment by sebbader** [comment]
By the way, a workaround for this problem is also the set "@type" attributes explicitly:
```
"ids:securityProfile" : {
    "@id" : "https://w3id.org/idsa/code/BASE_SECURITY_PROFILE",
    "@type": "idsc:SecurityProfile"
  },
```

**Comment by jfernandezsqs** [comment]
This PR is not solving issue:
Update connector at Metadata Broker not working #93

**Review by SebastianOpriel — APPROVED** [review]
Thanks, looks good! I do not agree with @jfernandezsqs 
It works for me

**Comment by jfernandezsqs** [comment]
I had just a meeting with Sebastian Opriel and checked that it is working this pull request.
Update connector at Metadata Broker is now working and the connector is updated at the Metadata Broker.
Could you please upload this PR to master branch? Thanks in advance

**Pull request merged**
